theme = "light:monokai-custom-light.theme,dark:monokai-custom.theme"
font-size = 14
macos-titlebar-style = "tabs"
# gtk-titlebar-style = "tabs"
gtk-titlebar-hide-when-maximized = true
keybind = shift+insert=paste_from_clipboard
keybind = all:cmd+1=csi:27;3;49~
keybind = all:cmd+2=csi:27;3;50~
keybind = all:cmd+3=csi:27;3;51~
keybind = all:cmd+4=csi:27;3;52~
keybind = all:cmd+5=csi:27;3;53~
keybind = all:cmd+6=csi:27;3;54~
keybind = all:cmd+7=csi:27;3;55~
keybind = all:cmd+8=csi:27;3;56~
keybind = all:cmd+9=csi:27;3;57~
keybind = all:ctrl+shift+left=csi:1;6D
keybind = all:ctrl+shift+right=csi:1;6C
keybind = all:ctrl+shift+up=csi:1;6A
keybind = all:ctrl+shift+down=csi:1;6B
app-notifications = true
maximize = true
cursor-style = block
cursor-style-blink = false
shell-integration-features = no-cursor
window-theme = ghostty

# infocmp -x xterm-ghostty | ssh your-host -- tic -x -
shell-integration-features = ssh-terminfo,ssh-env
