# Monokai Custom

background = #2d2a2e
foreground = #fcfcfa
cursor-color = #c1c0c0

palette = 0=#2d2a2e
palette = 1=#ff6188
palette = 2=#a9dc76
palette = 3=#ffd866
palette = 4=#fc9867
palette = 5=#ab9df2
palette = 6=#78dce8
palette = 7=#a1a19f
palette = 8=#4b464d
palette = 9=#ff6188
palette = 10=#a9dc76
palette = 11=#ffd866
palette = 12=#fc9867
palette = 13=#ab9df2
palette = 14=#78dce8
palette = 15=#fcfcfa

selection-background = #5b595c
selection-foreground = #fcfcfa
bold-color = #78dce8

