[/]
app-factors={'google-chrome': 0.25, 'chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default': 0.25}
global-factor=1.0
h-app-factors={'google-chrome': 0.25, 'chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default': 0.25}
h-global-factor=1.0
