[/]
app-factors={'google-chrome': 0.15, 'chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default': 0.15}
global-factor=0.5
h-app-factors={'google-chrome': 0.15, 'chrome-cinhimbnkkaeohfgghhklpknlkffjgod-Default': 0.15}
h-global-factor=0.5
