[tools]
node = "lts"
go = "latest"
rust = "stable"
python = "latest"
uv = "latest"
ripgrep = "latest"
gh = "latest"
jq = "latest"
"npm:pyright" = "latest"
rust-analyzer = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:bash-language-server" = "latest"
